### ISSUE TITLE
Reproduce jigsaw results problem

### ISSUE THREAD

**Issue by ChienDuong** [liaopeiyuan/TransferDet#8]
I try to run jagsaw_0 to 6 to restore the original image and merge the bounding box. 
However, it turns out that many images have black areas.
![image](https://user-images.githubusercontent.com/28746224/100199984-92a2a380-2f30-11eb-8792-eb41677056f2.png)

Do you know, what is the reason for this problem?

**Comment by liaopeiyuan** [comment]
The blacked areas may be due to the 80/20 split I made. You can tweak the code by adding back the missing images.

**Comment by ChienDuong** [comment]
I see, thank you
